name: npreferences
description: A Flutter local storage using SharedPreferences for nft. This lib is created by nhancv.
version: 5.0.0
homepage: https://github.com/nhancv/npreferences

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
